skip_tags: true
cache:
  - C:\strawberry\perl\site
install:
  - cinst strawberryperl
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm NML/Danga-Socket-1.62-TRIAL.tar.gz NML/Proc-Guard-0.07_01.tar.gz
  - cpanm --installdeps .
build_script:
  - cpanm -v --test-only .
